<?php

namespace PB\PlayableBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaygroundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaygroundRepository extends EntityRepository
{
}
