pb_playable_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PBPlayableBundle:Default:index }

PBPlayableBundle_playground:
        resource: "@PBPlayableBundle/Resources/config/routing/playground.yml"
        prefix:   /playground