parameters:
#    pb_playable.example.class: PB\PlayableBundle\Example

services:
#    pb_playable.example:
#        class: %pb_playable.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
