playground:
    pattern:  /
    defaults: { _controller: "PBPlayableBundle:Playground:index" }
    requirements: { _method: get }

playground_show:
    pattern:  /{id}/show
    defaults: { _controller: "PBPlayableBundle:Playground:show" }

playground_new:
    pattern:  /new
    defaults: { _controller: "PBPlayableBundle:Playground:new" }

playground_create:
    pattern:  /create
    defaults: { _controller: "PBPlayableBundle:Playground:create" }
    requirements: { _method: post }

playground_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PBPlayableBundle:Playground:edit" }

playground_update:
    pattern:  /{id}/update
    defaults: { _controller: "PBPlayableBundle:Playground:update" }
    requirements: { _method: post|put }

playground_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PBPlayableBundle:Playground:delete" }
    requirements: { _method: post|delete }
