playground:
    pattern:  /
    defaults: { _controller: "PBPlayableBundle:Playground:list" }
    requirements: { _method: get }

playground_show:
    pattern:  /{id}
    defaults: { _controller: "PBPlayableBundle:Playground:show" }

playground_create:
    pattern:  /
    defaults: { _controller: "PBPlayableBundle:Playground:create" }
    requirements: { _method: post }

playground_update:
    pattern:  /{id}
    defaults: { _controller: "PBPlayableBundle:Playground:update" }
    requirements: { _method: put }

playground_delete:
    pattern:  /{id}
    defaults: { _controller: "PBPlayableBundle:Playground:delete" }
    requirements: { _method: delete }
